# Generated by Django 4.1.5 on 2023-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planned_cases/'),
        ),
    ]
